apiVersion: apps/v1
kind: DaemonSet
metadata: 
  name: deamon
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template: 
    metadata: 
      name: dae-template 
      labels:
        app: myapp
    spec:
      containers:
      - name: aws-con
        image: amazon/cloudwatch-agent:latest
        ports:
        - containerPort: 80