apiVersion: v1
kind: Pod
metadata: 
  name: pvc-pod
  labels:
    app: myapp
spec:
  volumes: 
  - name: my-vol
    persistentVolumeClaim: 
      claimName: my-pvc
  containers:
  - name: pvc-pod
    image: nginx
    ports:
      containerPort: 80
    volumeMounts:
      name: my-vol
      mountPath: /usr/share/nginx/html/
