apiVersion: v1
kind: PersistentVolume
metadata: 
  name: my-pv
  labels: 
    app: myapp
spec: 
  capacity: 
    storage: 10Gi
  accessModes: 
    ReadWriteOnce
  StorageClassName: standard
  volumeMode: filesystem
  PersistentVolumeReclaimPolicy: Retain
  hostPath: 
    path: /mnt/data