apiVersion: v1
kind: Pod
metadata:
  name: sec-pod
spec:
  containers:
  - name: con
    image: nginx
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef: 
          name: db-sec
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-sec
          key: password