apiVersion: v1
kind: Pod
metadata: 
  name: pods
  labels:
    app :myapp
spec:
  tolerations:
  - key: "prod"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  containers:
  - name: con
    image: nginx
    ports:
    - containerPort: 80